#!/bin/bash

docker run -d -v /MountPoint --name myalpes alpine /bin/ash tail -f /dev/null
docker exec -it myalpes /bin/ash -c "echo 'WARNING: ret pointer is null' >/MountPoint/test.py"
docker commit myalpes myalpine:v12
docker export myalpes > myfile.tar
cat myfile.tar | docker import - myalpine:v12
docker login -u <docker_hub_account> -p <password>
docker image tag myalpine:v12 <docker_hub_account>/myalpine:v12
docker push <docker_hub_account>/myalpine

